language: php
php:
 - '7.1'

branches:
  only:
    - master


before_script:
  - sudo apt-get update
  - composer install


script: phpunit --configuration phpunit.xml --coverage-text

after_success:
    - bash <(curl -s https://codecov.io/bash)
